FROM magickml/magick:latest

ARG GITHUB_TOKEN
ARG BRANCH=development

ARG RAILWAY_GIT_COMMIT_SHA
# Configure git to use the token
RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
RUN git clone --branch ${BRANCH} --depth 1 https://www.github.com/oneirocom/magick.git /app

WORKDIR /app

RUN npm install

RUN npm run build-connector

ENTRYPOINT [ "npm", "run" ]
CMD [ "start-connector" ]